package morse

var (
	A = FromCodeString("・－")
	B = FromCodeString("－・・・")
	C = FromCodeString("－・－・")
	D = FromCodeString("－・・")
	E = FromCodeString("・")
	F = FromCodeString("・・－・")
	G = FromCodeString("－－・")
	H = FromCodeString("・・・・")
	I = FromCodeString("・・")
	J = FromCodeString("・－－－")
	K = FromCodeString("－・－")
	L = FromCodeString("・－・・")
	M = FromCodeString("－－")
	N = FromCodeString("－・")
	O = FromCodeString("－－－")
	P = FromCodeString("・－－・")
	Q = FromCodeString("－－・－")
	R = FromCodeString("・－・")
	S = FromCodeString("・・・")
	T = FromCodeString("－")
	U = FromCodeString("・・－")
	V = FromCodeString("・・・－")
	W = FromCodeString("・－－")
	X = FromCodeString("－・・－")
	Y = FromCodeString("－・－－")
	Z = FromCodeString("－－・・")

	One   = FromCodeString("・－－－－")
	Two   = FromCodeString("・・－－－")
	Three = FromCodeString("・・・－－")
	Four  = FromCodeString("・・・・－")
	Five  = FromCodeString("・・・・・")
	Six   = FromCodeString("－・・・・")
	Seven = FromCodeString("－－・・・")
	Eight = FromCodeString("－－－・・")
	Nine  = FromCodeString("－－－－・")
	Zero  = FromCodeString("－－－－－")

	Space = Code{WordSpace}

	Period       = FromCodeString("・－・－・－")
	Comma        = FromCodeString("－－・・－－")
	QuestionMark = FromCodeString("・・－－・・")
	Dash         = FromCodeString("－・・・・－")
	ForwardSlash = FromCodeString("－・・－・")
	At           = FromCodeString("・－－・－・")
	LeftBracket  = FromCodeString("－・－－・")
	RightBracket = FromCodeString("－・－－・－")
)

func init() {
	Dictionary.Add('a', A)
	Dictionary.Add('b', B)
	Dictionary.Add('c', C)
	Dictionary.Add('d', D)
	Dictionary.Add('e', E)
	Dictionary.Add('f', F)
	Dictionary.Add('g', G)
	Dictionary.Add('h', H)
	Dictionary.Add('i', I)
	Dictionary.Add('j', J)
	Dictionary.Add('k', K)
	Dictionary.Add('l', L)
	Dictionary.Add('m', M)
	Dictionary.Add('n', N)
	Dictionary.Add('o', O)
	Dictionary.Add('p', P)
	Dictionary.Add('q', Q)
	Dictionary.Add('r', R)
	Dictionary.Add('s', S)
	Dictionary.Add('t', T)
	Dictionary.Add('u', U)
	Dictionary.Add('v', V)
	Dictionary.Add('w', W)
	Dictionary.Add('x', X)
	Dictionary.Add('y', Y)
	Dictionary.Add('z', Z)

	Dictionary.Add('1', One)
	Dictionary.Add('2', Two)
	Dictionary.Add('3', Three)
	Dictionary.Add('4', Four)
	Dictionary.Add('5', Five)
	Dictionary.Add('6', Six)
	Dictionary.Add('7', Seven)
	Dictionary.Add('8', Eight)
	Dictionary.Add('9', Nine)
	Dictionary.Add('0', Zero)

	Dictionary.Add(' ', Space)

	Dictionary.Add('.', Period)
	Dictionary.Add(',', Comma)
	Dictionary.Add('?', QuestionMark)
	Dictionary.Add('-', Dash)
	Dictionary.Add('/', ForwardSlash)
	Dictionary.Add('@', At)
	Dictionary.Add('(', LeftBracket)
	Dictionary.Add(')', RightBracket)

	/* todo uncomment once jp is handled properly
	Dictionary.AddCodeString('イ',"・－")
	Dictionary.AddCodeString('ロ',"・－・－")
	Dictionary.AddCodeString('ハ',"－・・・")
	Dictionary.AddCodeString('ニ',"－・－・")
	Dictionary.AddCodeString('ホ',"－・・")
	Dictionary.AddCodeString('ヘ',"・")
	Dictionary.AddCodeString('ト',"・・－・・")
	Dictionary.AddCodeString('チ',"・・－・")
	Dictionary.AddCodeString('リ',"－－・")
	Dictionary.AddCodeString('ヌ',"・・・・")
	Dictionary.AddCodeString('ル',"－・－－・")
	Dictionary.AddCodeString('ヲ',"・－－－")
	Dictionary.AddCodeString('ワ',"－・－")
	Dictionary.AddCodeString('カ',"・－・・")
	Dictionary.AddCodeString('ヨ',"－－")
	Dictionary.AddCodeString('タ',"－・")
	Dictionary.AddCodeString('レ',"－－－")
	Dictionary.AddCodeString('ソ',"－－－・")
	Dictionary.AddCodeString('ツ',"・－－・")
	Dictionary.AddCodeString('ネ',"－－・－")
	Dictionary.AddCodeString('ナ',"・－・")
	Dictionary.AddCodeString('ラ',"・・・")
	Dictionary.AddCodeString('ム',"－")
	Dictionary.AddCodeString('ウ',"・・－")
	Dictionary.AddCodeString('ヰ',"・－・・－")
	Dictionary.AddCodeString('ノ',"・・－－")
	Dictionary.AddCodeString('オ',"・－・・・")
	Dictionary.AddCodeString('ク',"・・・－")
	Dictionary.AddCodeString('ヤ',"・－－")
	Dictionary.AddCodeString('マ',"－・・－")
	Dictionary.AddCodeString('ケ',"－・－－")
	Dictionary.AddCodeString('フ',"－－・・")
	Dictionary.AddCodeString('コ',"－－－－")
	Dictionary.AddCodeString('エ',"－・－－－")
	Dictionary.AddCodeString('テ',"・－・－－")
	Dictionary.AddCodeString('ア',"－－・－－")
	Dictionary.AddCodeString('サ',"－・－・－")
	Dictionary.AddCodeString('キ',"－・－・・")
	Dictionary.AddCodeString('ユ',"－・・－－")
	Dictionary.AddCodeString('メ',"－・・・－")
	Dictionary.AddCodeString('ミ',"・・－・－")
	Dictionary.AddCodeString('シ',"－－・－・")
	Dictionary.AddCodeString('ヱ',"・－－・・")
	Dictionary.AddCodeString('ヒ',"－－・・－")
	Dictionary.AddCodeString('モ',"－・・－・")
	Dictionary.AddCodeString('セ',"・－－－・")
	Dictionary.AddCodeString('ス',"－－－・－")
	Dictionary.AddCodeString('ン',"・－・－・")
	Dictionary.AddCodeString('゛',"・・")
	Dictionary.AddCodeString('゜',"・・－－・")
	*/
}
